version: 2.1

jobs:
  build-package:
    macos:
      xcode: 14.0.1

    steps:
      - checkout
      - run:
          name: Build Package
          command: swift build -v

  test-package:
    macos:
      xcode: 14.0.1

    steps:
      - checkout
      - run:
          name: Test Package
          command: swift test -v

workflows:
  build-test:
    jobs:
      - build-package:
          filters:
            branches:
              only:
                - master
      - test-package:
          filters:
            branches:
              only:
                - master
          requires:
            - build-package
