version: 2.1

jobs:
  build-test-14:
    macos:
      xcode: 14.0.1

    steps:
      - checkout
      - run:
          name: Build Package
          command: swift build -v
      - run:
          name: Test Package
          command: swift test -v

  build-test-13:
    macos:
      xcode: 13.4.1

    steps:
      - checkout
      - run:
          name: Build Package
          command: swift build -v
      - run:
          name: Test Package
          command: swift test -v

  build-test-12:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run:
          name: Build Package
          command: swift build -v
      - run:
          name: Test Package
          command: swift test -v

workflows:
  build-test:
    jobs:
      - build-test-14:
          filters:
            branches:
              only:
                - master
      - build-test-13:
          filters:
            branches:
              only:
                - master
      - build-test-12:
          filters:
            branches:
              only:
                - master
